### ISSUE TITLE
NullPointerException when version is omitted and no default version is set

### ISSUE THREAD

**Issue by alechenninger** [lightblue-platform/lightblue-rest#127]
I think maybe there could be a more specific exception for this? Right now you just get a 500 with:

{"errors":[{"objectType":"error","context":"rest/FindCommand/termsAcknowledgementJDBC","errorCode":"rest-crud:RestFindError","msg":"java.lang.NullPointerException"}],"status":"ERROR"}

**Comment by luan-cestari** [comment]
This behavior might be due the lines 62 and 64 (commented in the snippet of FindCommand class' code) which the root cause are the invocation of  BasicProjection.fromJson(BasicProjection.java:38) or  AbstractRestCommand.validateReq(AbstractRestCommand.java:106) methods. I think we can have two different approach to solve this issue following what we have been doing. One is to have a try/catch for line 62 and another for 64 to make sure that if any of them thrown an Exception (not an lightblue's Error) we can generalize the problem and omit the technical problem of the Exception, for instance, we can claim an invalid JSON on line 62 and an invalid request on the line 64. 

The other approach that I have in mind is to use the FindCommand's Error catch mechanism. So we would have to work on the root of the problem an make sure that I doesn't throw an Exception, but a meaningful error instead. The only concern that I have for this approach is that the errorCode could be not accurate if we have the same methods used by metadata classes as well.

```
        try {
            FindRequest ireq = getJsonTranslator().parse(FindRequest.class,JsonUtils.json(request)); // #62
            LOGGER.debug("Find request:{}", ireq);
            validateReq(ireq, entity, version); // #64
            addCallerId(ireq);
            Response r = getMediator().find(ireq);
            return new CallStatus(r);
        } catch (Error e) {
            LOGGER.error("find failure: {}", e);
            return new CallStatus(e);
        } catch (Exception e) {
            LOGGER.error("find failure: {}", e);
            return new CallStatus(Error.get(RestCrudConstants.ERR_REST_FIND, e.toString()));
        }
```

**Comment by luan-cestari** [comment]
Made the https://github.com/lightblue-platform/lightblue-rest/pull/137 to fix the issue
