### ISSUE TITLE
Please add notification hook

### ISSUE THREAD

**Issue by alechenninger** [lightblue-platform/lightblue-rest#190]
https://github.com/esbtools/lightblue-notification-hook

It's not published on Maven central yet, but we'll need this added so it is deployable when it is.

**Comment by dcrissman** [comment]
No longer required. Instead have your artefact generate an rpm that contains only your plugin's code and any required dependencies that are not already part of lightblue (So lightblue-ldap needs the ldap client library for example, but not lightblue-core because it will be provided).

For an example, see https://github.com/lightblue-platform/lightblue-audit-hook/pull/61

If you land your rpm in '/usr/share/java/lightblue', then no further action will be required. If you land the rpm elsewhere, then some configuration will be needed.

**Comment by alechenninger** [comment]
Awesome! Thanks!
